name: power
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - pip
  - pip:
    - -e ./data-downloader-package
    - -e ./jwm-data-downloader
    - jupytext
    - python-dotenv==1.0.0
    - plotly
    - statsmodels
    - matplotlib
    - tqdm
